name: Build Gold APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npx expo export --platform web
      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: PesaGuard-Build
          path: dist
